name: Docker Build/Publish Image

on:
  push:
    branches:
    - "main"
    tags:
    - '[0-9]+\.[0-9]+\.[0-9]+'   # Match major.minor.patch (e.g., 0.6.1)
    - '[0-9]+\.[0-9]+'           # Match major.minor (e.g., 0.6)

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5.6.1
      with:
        images: gfsolone/amamilano
        tag-match: '[0-9]+\.[0-9]+(\.[0-9]+)?'

    - name: Set up QEMU
      uses: "docker/setup-qemu-action@v3.6.0"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to DockerHub
      if: github.ref != 'refs/heads/main'   # Only on tag, not regular push
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: "docker/build-push-action@v6.13.0"
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: ${{ github.ref != 'refs/heads/main' }}   # Only on tag, not regular push
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}

    - name: Update repo description
      uses: peter-evans/dockerhub-description@v4.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: gfsolone/amamilano
        short-description: ${{ github.event.repository.description }}
      if: github.ref != 'refs/heads/main'   # Only on tag, not regular push
