name: Docker Build/Publish Image

on:
  workflow_run:
    workflows: ["Auto Release on Version Change"]
    types:
      - completed
    branches:
<<<<<<< HEAD
      - master
      
=======
    - "main"
    tags:
    - '[0-9]+\.[0-9]+\.[0-9]+'   # Match major.minor.patch (e.g., 0.6.1)
    - '[0-9]+\.[0-9]+'           # Match major.minor (e.g., 0.6)

>>>>>>> parent of a64ffcf (Update dockerbuild.yml)
jobs:
  docker:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Get tag from previous workflow
        run: |
          # Ottieni l'ultimo tag creato
          LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)
          if [ -z "$LATEST_TAG" ]; then
            echo "No tags found. Exiting."
            exit 1
          fi
          echo "Using latest tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: gfsolone/amamilano
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            # Usa il tag ottenuto dal workflow precedente
            type=raw,value=${{ env.LATEST_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4.0.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: gfsolone/amamilano
          short-description: ${{ github.event.repository.description }}
